CREATE USER tasks_user WITH PASSWORD 'your_password';

CREATE DATABASE tasks_db OWNER tasks_user;

GRANT ALL PRIVILEGES ON DATABASE tasks_db TO tasks_user;

\c tasks_db

GRANT USAGE, CREATE ON SCHEMA public TO tasks_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO tasks_user;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO tasks_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO tasks_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO tasks_user;
